---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /root/tomcat
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: /home/devops/tomcat/
        dest: /root/tomcat/
        owner: root
        group: root
        mode: '0777'
    - name: build container image
      shell: docker build -t tomcat /root/tomcat/
    - name: create docker container
      docker_container:
        name: tomcat-container
        published_ports: all
        image: tomcat
    - name: Check if container is running
      shell: docker ps
      register: container_info
    - name: List Container info
      debug: 
        msg: "{{container_info.stdout}}"
