---
- hosts: webserver
  become: true
  gather_facts: no
  tasks:
    - name: testing the variables
      debug:
        msg: "{{ check }}" 
       
    - name: Conditional logic
      debug:
        msg: "mysql is inside {{ check }}" 
      when: "'mysql' in check"         
  
    - name: create docker container
      docker_container:
        name: tomcat-container
        published_ports: all
        image: archanasuri/digialaitomcat
    - name: Check if container is running
      shell: docker ps
      register: container_info
    - name: List Container info
      debug: 
        msg: "{{container_info.stdout}}"
