name: Ansible Integration
on:
  repository_dispatch: 
    types: Container deployment


jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Container deployment
        run: echo The container deployment has started
                
      - name: check out
        uses: actions/checkout@v1
        
      - name: Authentication between control node and remote host
        run: ssh-copy-id root@35.230.118.86
         
      - name: Run Ansible Playbook
        run: sudo apt install ansible | sudo ansible-playbook container_playbook.yml

        
