name: Ansible Integration
on:
  repository_dispatch: 
    types: Container deployment


jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Container deployment
        run: echo The container deployment has started
                
      - name: check out
        uses: actions/checkout@v1
         
      - name: simple js action
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
            playbookName: 'container_playbook.yml'
