name: AnsibleIntegration
  
on:
  repository_dispatch: 
    types: Param Container deployment


jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Param Container deployment
        run: echo The container deployment has started
        
      - name:  Dynamic inpuut values
        #run: echo ${{env.Tool}}
        run: echo ${{ github.event.client_payload.test }}
        
      - name: second variable
        run: echo ${{ github.event.client_payload.test1 }}
                
      - name: check out
        uses: actions/checkout@v1
      
      - name: check ansible version
        run: ansible --version
        
      #- name: Authentication between control node and remote host
      #  run: ssh-copy-id root@35.239.200.96
         
      - name: Run Ansible Playbook
        run: sudo apt install ansible | sudo ansible-playbook -i hosts tomcat.yml --extra-vars "check=${{ github.event.client_payload.test }}"
